# Copyright (c) 2021 Qualcomm Technologies, Inc.
# All Rights Reserved.

help: False

checkpoint:
  init: resources/checkpoints/activitynet_checkpoint_25gmac.pth

##################
data:
  name: activitynet1.3

  path_frame: activitynet_v1.3/fps1_res350_hq/  # set the dataset dir
  path_split: data/activitynet/split_val_v1.3.txt
  path_label: data/activitynet/activity_net.v1-3.min.json
  path_classid: data/activitynet/classes.txt

  preprocessing:
    to_tensor: True
    resize: 224
    crop_center: 224
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  preprocessing_label:
    video_multihot_labels: ""
    one_hot_encoding: 200

  num_frames: 10
  num_workers: 0
  shuffle: False

###################
model:
  first_threshold: 0.99
  backbone:
    type: 2d
    name: torchvision.resnet50
    pretrained: True
    requires_grad: False
    truncate_modules: -1 # index indicates up until which layer to keep modules, i.e. -1 removes the classifier.
    output_dim: 2048

  pooling:
    name: max

  name: adaptive
  adaptive:
    input_order: [5, 0, 9, 2, 7, 4, 6, 3, 8, 1] #n10
  num_class: 200

