# Copyright (c) 2021 Qualcomm Technologies, Inc.
# All Rights Reserved.

help: False

checkpoint:
  init: resources/checkpoints/minikinetics_checkpoint_19.7gmac.pth

##################
data:
  name: minikinetics

  path_frame: /minikinetics/fps5_res256_hq/  # set the dataset dir
  path_split: data/minikinetics/split_val_minikinetics.txt
  path_label: data/minikinetics/kinetics_val.csv
  path_classid: data/minikinetics/minik_classInd.txt

  preprocessing:
    to_tensor: True
    resize: 224
    crop_center: 224
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  preprocessing_label:
    video_multihot_labels: ""
    one_hot_encoding: 200

  num_frames: 10
  num_workers: 0
  shuffle: False

###################
model:
  first_threshold: 0.95
  backbone:
    type: 2d
    name: torchvision.resnet50
    pretrained: True
    requires_grad: False
    truncate_modules: -1 # index indicates up until which layer to keep modules, i.e. -1 removes the classifier.
    output_dim: 2048

  pooling:
    name: max

  name: adaptive
  adaptive:
    input_order: [5, 0, 9, 2, 7, 4, 6, 3, 8, 1] #n10
  num_class: 200

